// Code generated by "stringer -type=TokenKind"; DO NOT EDIT.

package scanner

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ident-0]
	_ = x[LParen-1]
	_ = x[RParen-2]
	_ = x[LBrace-3]
	_ = x[RBrace-4]
	_ = x[Dot-5]
	_ = x[Comma-6]
	_ = x[Semicolon-7]
	_ = x[Plus-8]
	_ = x[Minus-9]
	_ = x[Star-10]
	_ = x[Slash-11]
	_ = x[EqEq-12]
	_ = x[Ne-13]
	_ = x[Gt-14]
	_ = x[Gte-15]
	_ = x[Lt-16]
	_ = x[Lte-17]
	_ = x[LNot-18]
	_ = x[LAnd-19]
	_ = x[LOr-20]
	_ = x[Eq-21]
	_ = x[Str-22]
	_ = x[Num-23]
	_ = x[Eof-24]
}

const _TokenKind_name = "IdentLParenRParenLBraceRBraceDotCommaSemicolonPlusMinusStarSlashEqEqNeGtGteLtLteLNotLAndLOrEqStrNumEof"

var _TokenKind_index = [...]uint8{0, 5, 11, 17, 23, 29, 32, 37, 46, 50, 55, 59, 64, 68, 70, 72, 75, 77, 80, 84, 88, 91, 93, 96, 99, 102}

func (i TokenKind) String() string {
	if i < 0 || i >= TokenKind(len(_TokenKind_index)-1) {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[i]:_TokenKind_index[i+1]]
}
